"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { formatPrice, propertyFacts, Property } from "@/app/lib/properties";
import { isSupabaseConfigured, supabase } from "@/app/lib/supabase";
type Mode = "rent" | "land";
export default function PropertyExplorePage({ mode }: { mode: Mode }) {
  const [city, setCity] = useState("All cities"); const [query, setQuery] = useState(""); const [properties, setProperties] = useState<Property[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (supabase) void supabase.from("properties").select("*").eq("listing_type", mode).order("created_at", { ascending: false }).then(({ data, error }) => error ? setError(error.message) : setProperties((data ?? []) as Property[])); }, [mode]);
  const cities = useMemo(() => [...new Set(properties.map((item) => item.city))], [properties]); const results = useMemo(() => properties.filter((item) => (city === "All cities" || item.city === city) && `${item.address} ${item.city}`.toLowerCase().includes(query.toLowerCase())), [city, properties, query]);
  const label = mode === "rent" ? "Rent" : "Land";
  return <main className="min-h-screen bg-surface text-on-surface"><header className="border-b border-outline-variant/40 bg-surface"><nav className="mx-auto flex h-20 max-w-container-max items-center justify-between px-margin-desktop"><Link href="/" className="font-headline-md text-headline-md font-bold text-primary">EstateFlow</Link><Link href="/admin" className="font-semibold text-primary">Admin</Link></nav></header><section className="bg-surface-container-low py-16"><div className="mx-auto max-w-container-max px-margin-desktop"><p className="text-label-bold font-label-bold uppercase text-secondary">{label} properties</p><h1 className="mt-3 font-display-lg text-display-lg">Browse {label.toLowerCase()} listings.</h1><div className="mt-8 grid gap-3 rounded-xl border bg-white p-3 md:grid-cols-[1fr_210px]"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="City, neighborhood, or address" className="rounded-lg border px-4 py-3"/><select value={city} onChange={(e) => setCity(e.target.value)} className="rounded-lg border bg-white px-4 py-3"><option>All cities</option>{cities.map((item) => <option key={item}>{item}</option>)}</select></div></div></section><section className="bg-surface-container-low py-20"><div className="mx-auto max-w-container-max px-margin-desktop"><p className="mb-8 text-on-surface-variant">{results.length} properties found</p>{!isSupabaseConfigured || error || results.length === 0 ? <div className="rounded-xl border border-dashed bg-white p-12 text-center text-on-surface-variant">{!isSupabaseConfigured ? "Configure Supabase in .env.local to load your properties." : error || "No published properties found yet."}</div> : <div className="grid gap-gutter md:grid-cols-2 xl:grid-cols-3">{results.map((item) => <Link key={item.id} href={`/properties/${item.id}`} className="property-card-shadow overflow-hidden rounded-xl bg-white"><img src={item.image_url || "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85"} alt={item.address} className="h-64 w-full object-cover"/><div className="p-stack-md"><h2 className="font-headline-md text-headline-md">{formatPrice(item)}</h2><p className="text-on-surface-variant">{item.address}</p><p className="mt-3 border-t pt-3 text-sm text-outline">{propertyFacts(item)}</p></div></Link>)}</div>}</div></section></main>;
}
