"use client";

import Link from "next/link";
import { useLanguage } from "@/app/components/language-provider";

export function SiteHeader() {
  const { locale, setLocale, t } = useLanguage();
  return <header className="border-b border-outline-variant/40 bg-surface"><nav className="mx-auto flex min-h-20 max-w-container-max flex-wrap items-center justify-between gap-4 px-margin-desktop py-3"><Link href="/" className="font-headline-md text-headline-md font-bold text-primary">EstateFlow</Link><div className="flex flex-wrap items-center justify-end gap-x-5 gap-y-2 text-sm font-semibold text-on-surface-variant"><div className="group relative"><Link href="/buy" className="flex items-center gap-1 hover:text-primary">{t("buy")}<span className="material-symbols-outlined text-base">expand_more</span></Link><div className="invisible absolute left-0 top-full z-50 mt-2 w-44 rounded-lg border border-outline-variant/40 bg-white py-2 opacity-0 shadow-lg transition-all group-hover:visible group-hover:opacity-100"><Link href="/buy?type=house" className="block px-4 py-2 hover:bg-surface-container-low hover:text-primary">{t("homes")}</Link><Link href="/buy?type=apartment" className="block px-4 py-2 hover:bg-surface-container-low hover:text-primary">{t("apartments")}</Link><Link href="/buy?type=villa" className="block px-4 py-2 hover:bg-surface-container-low hover:text-primary">{t("villas")}</Link></div></div><Link href="/rent" className="hover:text-primary">{t("rent")}</Link><Link href="/sell" className="hover:text-primary">{t("sell")}</Link><Link href="/land" className="hover:text-primary">{t("land")}</Link><Link href="/agents" className="hover:text-primary">{t("agents")}</Link><label className="flex items-center gap-2 text-primary"><span className="sr-only">{t("language")}</span><select value={locale} onChange={(event) => setLocale(event.target.value as typeof locale)} className="rounded-lg border border-outline-variant/60 bg-white px-2 py-1 text-sm font-semibold"><option value="en">English</option><option value="fr">Français</option><option value="ary">الدارجة</option></select></label></div></nav></header>;
}
