"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase";

type Request = { id: string; full_name: string; phone: string; address: string; description: string; status: "new" | "contacted" | "closed"; created_at: string; agents: { name: string } | null };

export default function SellRequestsPage() {
  const [requests, setRequests] = useState<Request[]>([]);
  const [allowed, setAllowed] = useState(false);
  const [notice, setNotice] = useState("");
  const load = async () => { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single(); if (profile?.role !== "admin") return; setAllowed(true); const { data, error } = await supabase.from("sell_requests").select("*, agents(name)").order("created_at", { ascending: false }); if (error) setNotice(error.message); else setRequests((data ?? []) as Request[]); };
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, []);
  const update = async (id: string, status: Request["status"]) => { if (!supabase) return; const { error } = await supabase.from("sell_requests").update({ status }).eq("id", id); if (error) setNotice(error.message); else await load(); };
  const remove = async (id: string) => { if (!supabase || !window.confirm("Delete this selling request permanently?")) return; const { error } = await supabase.from("sell_requests").delete().eq("id", id); if (error) setNotice(error.message); else { setNotice("Selling request deleted."); await load(); } };

  return <main className="min-h-screen bg-surface px-margin-desktop py-10 text-on-surface sm:py-16"><div className="mx-auto max-w-5xl"><Link href="/admin" className="font-bold text-primary">← Dashboard</Link><div className="mt-8"><p className="text-label-bold font-label-bold uppercase text-secondary">Inbox</p><h1 className="mt-2 font-display-lg text-display-lg">Selling requests</h1></div>{!allowed ? <p className="mt-8 rounded-2xl border border-dashed p-10 text-center">Sign in as an administrator first.</p> : <div className="mt-10 grid gap-4">{requests.length === 0 ? <p className="rounded-2xl border border-dashed p-10 text-center text-on-surface-variant">No selling requests yet.</p> : requests.map((request) => <article key={request.id} className="rounded-2xl border border-outline-variant/40 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-headline-md text-headline-md">{request.full_name}</h2><p className="mt-1 text-on-surface-variant">{request.phone} · {request.address}</p><p className="mt-2 text-sm text-outline">Assigned agent: {request.agents?.name ?? "Unassigned"}</p></div><div className="flex items-center gap-3"><select value={request.status} onChange={(event) => update(request.id, event.target.value as Request["status"])} className="rounded-lg border border-outline-variant/60 bg-white p-2 capitalize outline-none focus:border-primary"><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select><button type="button" onClick={() => remove(request.id)} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700 transition hover:bg-red-50">Delete</button></div></div><p className="mt-4 border-t border-outline-variant/40 pt-4 text-on-surface-variant">{request.description}</p><p className="mt-3 text-xs text-outline">Received {new Date(request.created_at).toLocaleString()}</p></article>)}</div>}{notice && <p className="mt-4 rounded-lg bg-error-container p-3 text-center text-on-error-container">{notice}</p>}</div></main>;
}
