"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase";
type Request = { id: string; full_name: string; phone: string; address: string; description: string; status: "new" | "contacted" | "closed"; created_at: string; agents: { name: string } | null };
export default function SellRequestsPage() {
  const [requests, setRequests] = useState<Request[]>([]); const [allowed, setAllowed] = useState(false); const [notice, setNotice] = useState("");
  const load = async () => { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single(); if (profile?.role !== "admin") return; setAllowed(true); const { data, error } = await supabase.from("sell_requests").select("*, agents(name)").order("created_at", { ascending: false }); if (error) setNotice(error.message); else setRequests((data ?? []) as Request[]); };
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, []);
  const update = async (id: string, status: Request["status"]) => { if (!supabase) return; const { error } = await supabase.from("sell_requests").update({ status }).eq("id", id); if (error) setNotice(error.message); else await load(); };
  return <main className="min-h-screen bg-surface px-margin-desktop py-16 text-on-surface"><div className="mx-auto max-w-4xl"><Link href="/admin" className="font-bold text-primary">← Dashboard</Link><h1 className="mt-6 text-center font-display-lg text-display-lg">Selling requests</h1>{!allowed ? <p className="mt-8 text-center">Sign in as an administrator first.</p> : <div className="mt-10 grid gap-4">{requests.length === 0 ? <p className="rounded-xl border border-dashed p-10 text-center text-on-surface-variant">No selling requests yet.</p> : requests.map((request) => <article key={request.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-headline-md text-headline-md">{request.full_name}</h2><p className="mt-1 text-on-surface-variant">{request.phone} · {request.address}</p><p className="mt-2 text-sm text-outline">Assigned agent: {request.agents?.name ?? "Unassigned"}</p></div><select value={request.status} onChange={(e) => update(request.id, e.target.value as Request["status"])} className="rounded-lg border p-2 capitalize"><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></div><p className="mt-4 border-t pt-4 text-on-surface-variant">{request.description}</p><p className="mt-3 text-xs text-outline">Received {new Date(request.created_at).toLocaleString()}</p></article>)}</div>}{notice && <p className="mt-4 text-center text-red-700">{notice}</p>}</div></main>;
}
