"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { formatPrice, Property } from "@/app/lib/properties";
import { supabase } from "@/app/lib/supabase";
import { SiteHeader } from "@/app/components/site-header";
import { useLanguage } from "@/app/components/language-provider";

type SearchMode = "sale" | "rent" | "reservation" | "land";
const heroImage = "https://pub-62bfc7a22a614d1592c5f36b18a45274.r2.dev/properties/islam-allam-nUETZNMjOuo-unsplash.jpg";

export default function HomePage() {
  const router = useRouter(); const { t } = useLanguage(); const [mode, setMode] = useState<SearchMode>("sale"); const [query, setQuery] = useState(""); const [properties, setProperties] = useState<Property[]>([]); const [agentCount, setAgentCount] = useState(0);
  useEffect(() => { if (!supabase) return; void Promise.all([supabase.from("properties").select("*").eq("published", true).order("created_at", { ascending: false }), supabase.from("agents").select("id", { count: "exact", head: true }).eq("published", true)]).then(([propertyResult, agentResult]) => { setProperties((propertyResult.data ?? []) as Property[]); setAgentCount(agentResult.count ?? 0); }); }, []);
  const cities = useMemo(() => new Set(properties.map((property) => property.city).filter(Boolean)).size, [properties]);
  function search(event: FormEvent) { event.preventDefault(); const destination = mode === "sale" ? "/buy" : `/${mode}`; router.push(query.trim() ? `${destination}?query=${encodeURIComponent(query.trim())}` : destination); }
  return <main className="min-h-screen bg-surface text-on-surface"><SiteHeader/>
    <section className="relative overflow-hidden bg-cover bg-center py-24 text-inverse-on-surface" style={{ backgroundImage: `url('${heroImage}')` }}><div className="absolute inset-0 bg-inverse-surface/55"/><div className="relative mx-auto max-w-container-max px-margin-desktop"><div className="max-w-2xl"><p className="text-label-bold font-label-bold uppercase text-secondary-fixed">{t("heroEyebrow")}</p><h1 className="mt-4 font-display-lg text-display-lg">{t("heroTitle")}</h1><p className="mt-5 max-w-xl text-body-lg text-surface-variant">{t("heroSubtitle")}</p><div className="mt-9 rounded-2xl bg-white p-4 text-on-surface shadow-xl"><div className="mb-4 flex flex-wrap gap-2">{(["sale", "rent", "land"] as SearchMode[]).map((item) => <button key={item} type="button" onClick={() => setMode(item)} className={`rounded-full px-4 py-2 text-sm font-bold ${mode === item ? "bg-primary text-on-primary" : "bg-surface-container-low"}`}>{t(item === "sale" ? "buy" : item)}</button>)}</div><form onSubmit={search} className="flex flex-col gap-3 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("addressPlaceholder")} className="min-w-0 flex-1 rounded-lg border border-outline-variant px-4 py-3 outline-none focus:border-primary"/><button className="rounded-lg bg-primary px-7 py-3 font-bold text-on-primary">{t("search")}</button></form></div></div></div></section>
    <section className="border-y border-outline-variant/20 bg-surface-container-low py-10"><div className="mx-auto grid max-w-container-max grid-cols-1 gap-8 px-margin-desktop text-center md:grid-cols-3"><Stat label={t("totalProperties")} value={properties.length}/><Stat label={t("cities")} value={cities}/><Stat label={t("agentsCount")} value={agentCount}/></div></section>
    <section className="py-20"><div className="mx-auto max-w-container-max px-margin-desktop"><div className="flex items-end justify-between gap-4"><div><p className="text-label-bold font-label-bold uppercase text-secondary">{t("latestListingsEyebrow")}</p><h2 className="mt-2 font-headline-lg text-headline-lg">{t("featured")}</h2></div><Link href="/buy" className="font-bold text-primary hover:underline">{t("buy")} →</Link></div>{properties.length === 0 ? <p className="mt-10 rounded-xl border border-dashed p-10 text-center text-on-surface-variant">{t("noProperties")}</p> : <div className="mt-10 grid gap-gutter md:grid-cols-2 xl:grid-cols-4">{properties.slice(0, 8).map((property) => <FeaturedCard key={property.id} property={property}/>)}</div>}<section className="mt-20 grid gap-10 rounded-2xl bg-surface-container-low p-8 md:grid-cols-[1.1fr_1fr] md:p-12"><div><p className="text-label-bold font-label-bold uppercase text-secondary">{t("aboutEyebrow")}</p><h2 className="mt-3 font-headline-lg text-headline-lg">{t("aboutTitle")}</h2><p className="mt-5 text-body-lg text-on-surface-variant">{t("aboutText")}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-white p-5"><span className="material-symbols-outlined text-3xl text-primary">home_work</span><h3 className="mt-3 font-headline-md text-headline-md">{t("verifiedListingsTitle")}</h3><p className="mt-2 text-sm text-on-surface-variant">{t("verifiedListingsText")}</p></div><div className="rounded-xl bg-white p-5"><span className="material-symbols-outlined text-3xl text-primary">support_agent</span><h3 className="mt-3 font-headline-md text-headline-md">{t("personalSupportTitle")}</h3><p className="mt-2 text-sm text-on-surface-variant">{t("personalSupportText")}</p></div></div></section></div></section>
    <footer className="bg-inverse-surface py-10 text-inverse-on-surface"><div className="mx-auto flex max-w-container-max flex-wrap items-center justify-between gap-4 px-margin-desktop"><p>© {new Date().getFullYear()} al salah — {t("allRightsReserved")}</p><div className="flex items-center gap-5"><Link href="/sell">{t("sell")}</Link><Link href="/agents">{t("agents")}</Link><Link href="/admin" className="rounded-lg border border-secondary-fixed px-4 py-2 font-bold text-secondary-fixed">{t("connect")}</Link></div></div></footer>
  </main>;
}

function FeaturedCard({ property }: { property: Property }) {
  const { t } = useLanguage();
  return <Link href={`/properties/${property.id}`} className="property-card-shadow overflow-hidden rounded-xl bg-white"><img src={property.image_url || heroImage} alt={property.address} className="h-56 w-full object-cover"/><div className="p-5"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-secondary-container/50 px-2.5 py-1 text-xs font-bold uppercase text-secondary">{property.listing_type}</span>{property.is_luxury && <span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-800">Luxury</span>}{property.is_good_deal && <span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800">Good deal</span>}</div><h3 className="mt-3 font-headline-md text-headline-md">{formatPrice(property)}</h3><p className="mt-2 flex items-center gap-1 text-sm font-semibold text-primary"><span className="material-symbols-outlined text-base">location_on</span>{property.city}</p><p className="mt-1 truncate text-sm text-on-surface-variant">{property.address}</p><div className="mt-4 flex flex-wrap gap-x-3 gap-y-2 border-t border-outline-variant/30 pt-3 text-sm text-outline">{property.bedrooms !== null && <span className="flex items-center gap-1"><span className="material-symbols-outlined text-base">bed</span>{property.bedrooms} {t("beds")}</span>}{property.bathrooms !== null && <span className="flex items-center gap-1"><span className="material-symbols-outlined text-base">bathtub</span>{property.bathrooms} {t("baths")}</span>}{property.area_m2 !== null && <span className="flex items-center gap-1"><span className="material-symbols-outlined text-base">square_foot</span>{new Intl.NumberFormat().format(property.area_m2)} m²</span>}</div></div></Link>;
}

function Stat({ label, value }: { label: string; value: number }) { const { t } = useLanguage(); return <div><p className="text-label-bold font-label-bold uppercase text-outline">{label}</p><p className="mt-2 font-display-lg text-display-lg text-primary">{new Intl.NumberFormat().format(value)}</p><p className="text-sm text-on-surface-variant">{t("liveDatabaseTotal")}</p></div>; }
