"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { isSupabaseConfigured, supabase } from "@/app/lib/supabase";
import { SiteHeader } from "@/app/components/site-header";
import { useLanguage } from "@/app/components/language-provider";

const adminWhatsAppNumber = process.env.NEXT_PUBLIC_ADMIN_WHATSAPP_NUMBER?.replace(/[^\d]/g, "");

export default function SellPage() {
  const { t } = useLanguage(); const [submitted, setSubmitted] = useState(false); const [notice, setNotice] = useState(""); const [sending, setSending] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase) return; const formElement = event.currentTarget; setSending(true); const form = new FormData(formElement); const request = { full_name: String(form.get("fullName")), phone: String(form.get("phone")), address: String(form.get("address")), description: String(form.get("description")) }; const { error } = await supabase.from("sell_requests").insert(request); setSending(false); if (error) { setNotice(`Could not send your request: ${error.message}`); return; } setSubmitted(true); formElement.reset(); if (adminWhatsAppNumber) { const text = `New selling consultation request\nName: ${request.full_name}\nPhone: ${request.phone}\nProperty: ${request.address}\nDetails: ${request.description}`; window.open(`https://wa.me/${adminWhatsAppNumber}?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer"); } else setNotice("Your request was saved. WhatsApp is not configured yet."); }
  return <main className="min-h-screen bg-surface text-on-surface"><SiteHeader/><section className="bg-surface-container-low py-16"><div className="mx-auto max-w-container-max px-margin-desktop"><p className="text-label-bold font-label-bold uppercase text-secondary">{t("sell")}</p><h1 className="mt-3 max-w-2xl font-display-lg text-display-lg">Tell us about your property.</h1><p className="mt-5 max-w-xl text-body-lg text-on-surface-variant">Share a few details and we&apos;ll help you take the next step toward selling with confidence.</p></div></section><section className="mx-auto grid max-w-container-max gap-12 px-margin-desktop py-16 lg:grid-cols-[minmax(0,1fr)_360px]">{!isSupabaseConfigured ? <p>Supabase is not configured.</p> : <form onSubmit={handleSubmit} className="rounded-xl border border-outline-variant/50 bg-white p-6 shadow-sm sm:p-8"><h2 className="font-headline-lg text-headline-lg">Property details</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Full name" name="fullName" type="text"/><Field label="Phone number" name="phone" type="tel"/></div><Field label="Property address" name="address" type="text"/><label className="mt-5 block text-sm font-bold">Property description<textarea required name="description" rows={6} className="mt-2 w-full rounded-lg border border-outline-variant/60 px-4 py-3 font-normal" placeholder="Property type, rooms, condition, and anything else you would like us to know."/></label><button disabled={sending} type="submit" className="mt-7 rounded-lg bg-primary px-7 py-3 font-bold text-on-primary disabled:opacity-50">{sending ? "Sending…" : "Request a selling consultation"}</button>{submitted && <p className="mt-4 rounded-lg bg-secondary-container px-4 py-3 text-sm font-semibold text-on-secondary-container">Thanks—we&apos;ve received your details.</p>}{notice && <p className="mt-4 rounded-lg bg-secondary-container px-4 py-3 text-sm font-semibold text-on-secondary-container">{notice}</p>}</form>}<aside className="h-fit rounded-xl bg-inverse-surface p-8 text-inverse-on-surface"><h2 className="font-headline-lg text-headline-lg">Meet a local agent.</h2><p className="mt-4 text-body-sm text-surface-variant">Get a personal opinion on pricing and the best plan for selling your home.</p><Link href="/agents" className="mt-7 inline-flex rounded-lg bg-white px-5 py-3 font-bold text-primary">{t("agents")}</Link></aside></section></main>;
}
function Field({ label, name, type }: { label: string; name: string; type: string }) { return <label className="block text-sm font-bold">{label}<input required name={name} type={type} className="mt-2 w-full rounded-lg border border-outline-variant/60 px-4 py-3 font-normal"/></label>; }
