"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Agent } from "@/app/lib/properties";
import { supabase } from "@/app/lib/supabase";
type AgentForm = { slug: string; name: string; city: string; title: string; bio: string; about: string; image_url: string; phone: string; email: string; experience: string; sales: string; languages: string; published: boolean };
const blank: AgentForm = { slug: "", name: "", city: "", title: "", bio: "", about: "", image_url: "", phone: "", email: "", experience: "", sales: "", languages: "", published: true };
export default function AdminAgentsPage() {
  const [agents, setAgents] = useState<Agent[]>([]); const [form, setForm] = useState<AgentForm>(blank); const [editingId, setEditingId] = useState<string | null>(null); const [notice, setNotice] = useState(""); const [allowed, setAllowed] = useState(false);
  const change = (key: keyof AgentForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const load = async () => { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single(); if (profile?.role !== "admin") return; setAllowed(true); const { data } = await supabase.from("agents").select("*").order("name"); setAgents((data ?? []) as Agent[]); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; const request = editingId ? supabase.from("agents").update(form).eq("id", editingId) : supabase.from("agents").insert(form); const { error } = await request; setNotice(error ? error.message : "Agent saved."); if (!error) { setForm(blank); setEditingId(null); await load(); } };
  const edit = (agent: Agent) => { setEditingId(agent.id); setForm({ slug: agent.slug, name: agent.name, city: agent.city, title: agent.title, bio: agent.bio ?? "", about: agent.about ?? "", image_url: agent.image_url ?? "", phone: agent.phone ?? "", email: agent.email ?? "", experience: agent.experience ?? "", sales: agent.sales ?? "", languages: agent.languages ?? "", published: agent.published }); };
  const remove = async (id: string) => { if (!supabase || !confirm("Delete this agent?")) return; const { error } = await supabase.from("agents").delete().eq("id", id); setNotice(error ? error.message : "Agent deleted."); if (!error) await load(); };
  return <main className="min-h-screen bg-surface px-margin-desktop py-16 text-on-surface"><div className="mx-auto max-w-4xl"><Link href="/admin" className="font-bold text-primary">← Dashboard</Link>{!allowed ? <p className="mt-8">Sign in as an administrator first.</p> : <><h1 className="mt-6 text-center font-display-lg text-display-lg">Manage agents</h1><p className="mt-2 text-center text-on-surface-variant">Create and maintain the public agent profiles.</p><form onSubmit={save} className="mx-auto mt-8 grid max-w-3xl gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><Field label="Slug" value={form.slug} onChange={(v) => change("slug", v)}/><Field label="Name" value={form.name} onChange={(v) => change("name", v)}/><Field label="City" value={form.city} onChange={(v) => change("city", v)}/><Field label="Title" value={form.title} onChange={(v) => change("title", v)}/><Field label="Short bio" value={form.bio} onChange={(v) => change("bio", v)}/><Field label="Photo URL" value={form.image_url} onChange={(v) => change("image_url", v)}/><Text label="Full description" value={form.about} onChange={(v) => change("about", v)}/><Text label="Languages" value={form.languages} onChange={(v) => change("languages", v)}/><Field label="Phone" value={form.phone} onChange={(v) => change("phone", v)}/><Field label="Email" value={form.email} onChange={(v) => change("email", v)}/><Field label="Experience" value={form.experience} onChange={(v) => change("experience", v)}/><Field label="Career sales" value={form.sales} onChange={(v) => change("sales", v)}/><label className="flex items-center gap-2"><input type="checkbox" checked={form.published} onChange={(e) => change("published", e.target.checked)}/> Published</label><div><button className="rounded-lg bg-primary px-5 py-3 font-bold text-on-primary">{editingId ? "Update agent" : "Add agent"}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(blank); }} className="ml-4 font-bold text-primary">Cancel</button>}</div></form>{notice && <p className="mt-4 text-center">{notice}</p>}<div className="mx-auto mt-10 grid max-w-3xl gap-3">{agents.map((agent) => <div key={agent.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><b>{agent.name}</b><p className="text-sm text-on-surface-variant">{agent.title} · {agent.city}</p></div><div className="flex gap-3"><button className="font-bold text-primary" onClick={() => edit(agent)}>Edit</button><button className="font-bold text-red-700" onClick={() => remove(agent.id)}>Delete</button></div></div>)}</div></>}</div></main>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm font-bold">{label}<input required={["Slug", "Name", "City", "Title"].includes(label)} value={value} onChange={(e) => onChange(e.target.value)} className="rounded-lg border p-3 font-normal"/></label>; }
function Text({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm font-bold">{label}<textarea value={value} onChange={(e) => onChange(e.target.value)} className="min-h-28 rounded-lg border p-3 font-normal"/></label>; }
